/**
 * 200 anlamli demo gonderi metni (8 kategori x 25)
 * img: oncelikli anlamli gorsel seed; cift siradaki gonderilerde gorsel kullanilir
 */
module.exports = {
  technology: [
    { t: 'MacBook M4 ile bir haftalik saha testi: pil 18 saate cikti, fan sesi neredeyse yok.', img: 'macbook-laptop-desk' },
    { t: 'React 19 ve Server Components gecisinde ekibimizin ogrendigi 5 ders.' },
    { t: 'Flutter ile tek kod tabanindan iOS/Android MVP teslim ettik, store onayi 48 saatte geldi.', img: 'mobile-app-smartphone' },
    { t: 'Kubernetes HPA ile gece trafik dalgasinda pod sayisini otomatik 3ten 12ye cikardik.', img: 'server-datacenter-cloud' },
    { t: 'Raspberry Pi ve MQTT ile bahce sulama otomasyonu kurduk, su tuketimi %30 azaldi.' },
    { t: 'Spring Boot 3 mikroservislerinde distributed tracing icin OpenTelemetry entegrasyonu tamam.', img: 'java-code-ide' },
    { t: 'Llama 3 Turkce QA veriseti ile fine-tune: F1 skoru %12 artti, halusinasyon azaldi.', img: 'ai-neural-network' },
    { t: 'AWS Lambda cold start icin provisioned concurrency denedik, P99 420msden 180mse indi.' },
    { t: 'Tasarim sistemimizde 40 bilesen WCAG AA uyumlu; kontrast testleri CIa baglandi.', img: 'ui-design-figma' },
    { t: 'Seed turunu kapattik: 12 kisilik ekip, B2B SaaS, ilk 50 odeme yapan musteri.' },
    { t: 'GitHub Actions ile staging deploy 12 dakikadan 3 dakikaya indi.', img: 'github-devops-pipeline' },
    { t: 'PostgreSQL partial index ile rapor sorgusu 8 saniyeden 0.7 saniyeye dustu.' },
    { t: 'TypeScript strict mode actiktan sonra production bug sayisi ikiye bolundu.' },
    { t: 'GraphQL N+1 sorununu DataLoader ile cozduk, API latency %40 iyilesti.', img: 'code-screen-programming' },
    { t: 'Redis cache invalidation stratejimizi dokumante ettik, stale read vakasi sifir.' },
    { t: 'Mobil uygulamada offline-first mimari: SQLite sync queue ile metroda da calisiyor.', img: 'mobile-offline-sync' },
    { t: 'Sentry ve structured logging ile incident MTTR 2 saatten 35 dakikaya indi.' },
    { t: 'Rust ile yazilan kritik modulu denedik; bellek kullanimi Go surumune gore %25 dusuk.', img: 'rust-programming-code' },
    { t: 'Erisilebilirlik audit: klavye ile tum form akisi tamamlandi, screen reader uyumlu.' },
    { t: 'Monorepo Turborepo gecisi: CI sure 28 dakikadan 11 dakikaya indi.' },
    { t: 'WebSocket ile canli bildirim gecikmesi 200ms altina indi, reconnect backoff eklendi.', img: 'websocket-realtime-app' },
    { t: 'Feature flag ile riskli rollout: %5 trafikte hata yok, tam acilis yarin.' },
    { t: 'Docker imaj boyutunu alpine + multi-stage ile 1.2GBden 280MBa indirdik.', img: 'docker-container-devops' },
    { t: 'Pair programming seansi: karmasik merge conflict 20 dakikada cozuldu.' },
    { t: 'Yeni stajyer onboarding checklist yayinlandi, ilk hafta setup suresi yarilandi.', img: 'team-onboarding-office' },
  ],
  sports: [
    { t: 'Derbi 3-2 bitti; ikinci yarida pres ve kanat bindirmesi maci cevirdi.', img: 'football-stadium-crowd' },
    { t: 'Sabah 8 km tempo kosu: nabiz zonu 4te kaldim, haftalik plana sadikim.' },
    { t: '30 gun yoga challenge gun 12: nefes + esneklik, bel agrisi belirgin azaldi.', img: 'yoga-meditation-studio' },
    { t: 'Halı saha finali cumartesi 21:00 — eksik pivot varsa yazin, forma hazir.' },
    { t: 'U16 basketbol kampinda pick-and-roll savunmasi ve iletisim calistik.', img: 'basketball-court-game' },
    { t: 'Valorant scrimde attack stratejimiz calisti; B site rush %70 basari.' },
    { t: 'Mac oncesi karbonhidrat yuklemesi ve hidrasyon plani paylasiyorum.', img: 'healthy-food-athlete' },
    { t: 'Penalti antrenmaninda 10 atistan 8 isabet — kaleci analizi eklendi.' },
    { t: 'Dinlenme gunu: hafif yuruyus + foam roller, overtraining riskine dikkat.' },
    { t: 'HIIT 4 haftalik programin 2. haftasi: VO2 max hissedilir artti.', img: 'hiit-workout-gym' },
    { t: 'Takim antrenmaninda pres oyunu denedik, rakip 3. dakikada hata yapti.' },
    { t: 'NBA final serisinde pick-and-roll savunma rotasyonu notlarim.', img: 'basketball-nba-arena' },
    { t: 'Pilates reformer yeni baslayanlar icin 45 dklik seans plani.' },
    { t: 'Mac sonrasi soguma kosusu ve protein alimi rutinim.' },
    { t: 'Futbol ayakkabisi secimi: krampon uzunlugu ve zemin tipi rehberi.', img: 'soccer-cleats-field' },
    { t: 'Yuzme teknik analizi: nefes ritmi duzelince 100m 8 saniye kisaldi.' },
    { t: 'Bisiklet turu 60 km: vites ve oturma pozisyonu ayari onemli.' },
    { t: 'Serbest atis rutini: ayni nefes, ayni ritim, %78 isabet.', img: 'free-throw-basketball' },
    { t: 'Takim ic callout listesi hazirladik; kisa komutlar kafa karisikligini azaltiyor.' },
    { t: 'Antrenman oncesi dinamik isinma protokolu — sakatlik riski dusuyor.' },
    { t: 'Kosu bandi yerine dis mekan interval: daha iyi tempo kontrolu.', img: 'outdoor-running-track' },
    { t: 'Sporcu beslenmesinde elektrolit dengesi: magnezyum ve potasyum notlari.' },
    { t: 'Voleybol manşet calismasi: omuz acma ve parmak hakimiyeti.' },
    { t: 'Esports takim toplantisi: harita veto ve ekonomi round planlari.', img: 'esports-gaming-setup' },
    { t: 'Yoga nefes egzersizi 4-7-8: stres seviyesi gun sonunda belirgin dusuyor.' },
  ],
  music: [
    { t: 'Cuma setlist: indie rock acilis, jazz fusion ikinci set, sahne 23:00.', img: 'dj-console-nightclub' },
    { t: 'Chopin Nocturne calisma: yavas metronom 60 BPM ile ifade calisiyorum.' },
    { t: 'Studyo kaydi bitti; yeni single gelecek hafta Spotify ve Apple Musicta.', img: 'rock-guitar-studio' },
    { t: 'Bach Cello Suite No.1 performansim cumartesi salonda, prova kaydi ekte.' },
    { t: 'Vinil plak koleksiyonuma 1973 baski Pink Floyd ekledim, temizlik videosu cektim.', img: 'vinyl-record-collection' },
    { t: 'Canli performans enerjisi icin monitor mix ayarlarini paylasiyorum.' },
    { t: 'Spotify Wrapped oncesi en cok dinledigim 5 sanatci ve nedenleri.', img: 'music-streaming-headphones' },
    { t: 'Metronom olmadan tempo tutma: ic ritim ve vuruş hissi calismasi.' },
    { t: 'Online masterclass: Beethoven sonata formu ve tema gelistirme.' },
    { t: 'Sahne monitoru gecikme sorunu cozuldu; IEM ile temiz miks.', img: 'live-concert-stage' },
    { t: 'Akustik gitar tel degisimi ve action ayari rehberi.' },
    { t: 'Caz harmonisi: ii-V-I gecislerinde voicing secimi.' },
    { t: 'Ev studyosunda akustik panel kurulumu: yanki %40 azaldi.', img: 'home-studio-acoustic' },
    { t: 'Koro provasi: soprano ve alto dengesi icin dinleme listesi.' },
    { t: 'Elektronik muzik prodüksiyonunda sidechain compression ipucu.' },
    { t: 'Davul tekniği: ghost note ile groove derinligi.', img: 'drums-kit-practice' },
    { t: 'Festival backstage notlari: ses check sureci ve rider listesi.' },
    { t: 'Klasik gitar parmak teknikleri: arpej calismasi 20 dk/gun.' },
    { t: 'Sampling etik ve telif: ticari proje icin lisans sureci.', img: 'sampler-music-production' },
    { t: 'Mikrofon polar pattern secimi: vokal kayit icin kardioid.' },
    { t: 'Orkestra prova: Vivaldi Four Seasons 3. bolum tempo birlestirme.' },
    { t: 'Baglama ayari: komşu tel uyumu ve perde kontrolu.' },
    { t: 'Konser fotograflariyla birlikte setlist arsivi yayinladim.', img: 'concert-audience-lights' },
    { t: 'Muzik teorisi: modülasyon teknikleri ozet tablo.' },
    { t: 'Jam session daveti: pazar 19:00, enstrumanini getir, amator profesyonel fark etmez.' },
  ],
  art: [
    { t: 'Dijital portre serisi 3: Procreate karisik firca ve renk katmani. #art', img: 'digital-art-tablet' },
    { t: 'Kadikoy duvarina Istanbul silueti mural — 4 gun, hava durumu kritik.' },
    { t: 'Seramik atolyesi acilis cumartesi: ilk 20 kisi ucretsiz deneme.', img: 'pottery-clay-ceramic' },
    { t: 'Osmanli minyatur sergisi acildi; rehberli tur saat 14:00.', img: 'museum-gallery-exhibit' },
    { t: 'Dogal isikta portre: golden hour 18 dk, reflektor kullanimi.' },
    { t: 'Yeni siir kitabi matbaadan cikti; lansman pazar Nadir Kitap.' },
    { t: 'Renk teorisi: komplementer palet secimi ve kontrast orani.', img: 'color-palette-art' },
    { t: 'Raku firing ile seramik glazur denemesi — catlak desenleri harika.' },
    { t: 'Cagdas Turk resmi sergisi: 45 sanatci, ucretsiz giris ogrencilere.' },
    { t: 'NFT mi geleneksel galeri mi? Sanatci olarak gercekci karsilastirma.', img: 'digital-art-nft' },
    { t: 'Mural sketch calismalari tamam; boya isine pazartesi basliyoruz.' },
    { t: 'Kafe okumasi: 20 kisi, samimi ortam, yeni siirlerden uc parca.' },
    { t: 'Akrilik tuvalde katmanlama tekigi: kuruma suresine dikkat.', img: 'acrylic-painting-canvas' },
    { t: 'Fotograf kompozisyonu: uc parca kurali ve negatif alan.' },
    { t: 'Heykel atolyesinde kalip alma sureci ilk kez denedim.' },
    { t: 'Sanat tarihi ders notlari: Bauhaus ve islevsel tasarim.', img: 'bauhaus-design-art' },
    { t: 'Kaligrafi calismasi: ince uç ve mürekkep viskozitesi.' },
    { t: 'Grafik novel storyboard: panel ritmi ve diyalog yerlesimi.' },
    { t: 'Sergi katalog tasarimi bitti; tipografi ve bosluk dengesi.', img: 'exhibition-catalog-design' },
    { t: 'Sokak fotografciligi: izin ve etik cerceve notlarim.' },
    { t: 'Cam fusing deneyi: sicaklik egrisi ve renk karisimlari.' },
    { t: 'Illüstrasyon komisyonu teslim: musteri revizyonu 2 turda tamam.', img: 'illustration-commission-art' },
    { t: 'Atolye ziyareti: ogrenci cizimlerinden secilmis 12 eser.' },
    { t: 'Sanat elestirisi yazisi: yerel galeri acilis sergisine bakis.' },
    { t: 'Eskiz defteri taramalari yayinlandi; karakter tasarimi sureci gorunur.', img: 'sketchbook-drawing-artist' },
  ],
  science: [
    { t: 'CRISPR deneyi: kurakliga dayanikli bitki gen ekspresyonu %30 artti.', img: 'laboratory-microscope-science' },
    { t: 'Kuantum fizigi dersi: Bohr modeli ve ogrenci deneyleri.', img: 'physics-blackboard-teaching' },
    { t: '1970-2026 iklim verisi: sicaklik trendi ve guven araligi grafigi.' },
    { t: 'NASA Mars rover yeni kaya ornegi: jeoloji ekibi analiz baslatti.', img: 'mars-planet-space' },
    { t: 'Hucre kulturunde kontaminasyon onleme protokolu guncellendi.' },
    { t: 'Python pandas ile 1M satir veri temizleme pipeline dokumante edildi.', img: 'data-analysis-charts' },
    { t: 'Overfitting belirtisi: train yuksek, validation dusuk — cozum onerileri.' },
    { t: 'Ogrencilerle basit elektrik devresi: Ohm kanunu deneyi.' },
    { t: 'Peer review surecinde metodoloji ve tekrarlanabilirlik kontrol listesi.', img: 'research-paper-science' },
    { t: 'Deney etik kurulu basvurusu onaylandi; insan katilimli anket basliyor.' },
    { t: 'Istatistikte yanıltici eksen: grafik okuma atolyesi notlari.' },
    { t: 'Genetik dizi analizi: BLAST araması ve homoloji yorumu.', img: 'dna-sequence-bioinformatics' },
    { t: 'Radyasyon guvenligi egitimi tamamlandi; laboratuvar rozet yenilendi.' },
    { t: 'Iklim modeli senaryosu RCP4.5: bolgesel yagis projeksiyonu.' },
    { t: 'Fizikoloji: uyku ve performans iliskisi meta-analiz ozeti.', img: 'sleep-study-science' },
    { t: 'Kimya deneyi: titrasyon egri yorumlama adimlari.' },
    { t: 'Astronomi gozlemi: Jupiter uydulari ve teleskop ayari.' },
    { t: 'Makine ogrenmesi: cross-validation ve hyperparameter arama.', img: 'machine-learning-diagram' },
    { t: 'Bilim okuryazarligi kaynak listesi ogrencilerle paylasildi.' },
    { t: 'Ekosistem gozlemi: kus sayimi ve habitat kaydi saha notlari.' },
    { t: 'Nanoparçacik sentezi: karakterizasyon SEM goruntuleri.', img: 'sem-microscope-lab' },
    { t: 'Ogrenci proje yarismasi: yenilenebilir enerji mini turbin modeli.' },
    { t: 'Bilim tarihi: Darwin ve dogal secilim ders slaytlari.' },
    { t: 'Veri seti acik paylasim: etiketleme standardi ve lisans (CC-BY).', img: 'open-data-science' },
    { t: 'Laboratuvar atik yonetimi: kimyasal depolama kurallari hatirlatmasi.' },
  ],
  travel: [
    { t: 'Kapadokya balon turu: gunes dogumunda 1200m, omru boyu deneyim.', img: 'cappadocia-balloon-sky' },
    { t: 'Karadeniz yayla rotasi 10 gun, 800 km van — yol ve kamp notlari.', img: 'mountain-road-van' },
    { t: 'Tokyo 5 gun + Kyoto 3 gun: sakura tahmini Nisan ikinci hafta.' },
    { t: 'Uludag zirve 2543m: kar var, crampon ve katmanli giyim sart.', img: 'hiking-mountain-snow' },
    { t: 'Kaputas plaji: yaz oncesi sakin, sabah 07:00 en iyi isik.' },
    { t: 'Amsterdam bisiklet turu: kanallar, tulipanlar ve muzeler.', img: 'amsterdam-canal-bike' },
    { t: 'Pamukkale traverten: gun batiminda renkler baska guzel.' },
    { t: 'Likya yolu 4. etap Kalkan-Kas 20 km, su noktaları isaretli.', img: 'coastal-hike-trail' },
    { t: 'Balkanlar turu: Belgrad, Saraybosna, Mostar — vize ve butce tablosu.' },
    { t: 'Van life icinde 3 gizli kamp noktasi paylasiyorum (harita yorumda).', img: 'van-camping-nature' },
    { t: 'Efes antik kent rehberli tur: sabah erken giris kalabalik azaltiyor.' },
    { t: 'Hostel mi otel mi: butce seyahatte karar matrisi.' },
    { t: 'Seyahat cantasi 7 kg ile 2 hafta: minimal liste.', img: 'travel-backpack-light' },
    { t: 'Igdir Agri dagi gunes dogumu fotografi: tripod ve katman onemli.' },
    { t: 'Kars kis manzarasi: kar taneleri makro cekim.' },
    { t: 'Girit adasi road trip: plajlar ve yerel taverna onerileri.', img: 'greece-island-beach' },
    { t: 'Istanbul hafta sonu: Kadikoy-Moda yuruyus rotasi.' },
    { t: 'Ucuz ucak bileti: esnek tarih ve alarm kurma taktikleri.' },
    { t: 'Seyahat sigortasi: saglik ve iptal teminat karsilastirmasi.', img: 'travel-insurance-passport' },
    { t: 'Norvec fiyordlari: feribot rezervasyonu ve konaklama.' },
    { t: 'Marrakech medina: pazarlik ve guvenlik ipuclari.' },
    { t: 'Gurcistan Batum: deniz kenari ve mutfak turu.', img: 'batumi-seafood-travel' },
    { t: 'Yurt disi SIM ve eSIM: roaming maliyeti karsilastirmasi.' },
    { t: 'Fotograf seyahati: ucak penceresinden cekim ISO ayari.' },
    { t: 'Yerel kultur: selam verme ve kiyafet adabina kisa rehber.', img: 'local-culture-travel' },
  ],
  food: [
    { t: 'Ev yapimi Kayseri mantisi: aci sos ve sarimsakli yogurt dengesi.', img: 'turkish-manti-food' },
    { t: 'Cikolatali sufle: disi citir, ici akmali — firin sicakligi kritik.', img: 'chocolate-souffle-dessert' },
    { t: 'Sokak lezzeti kokorec turu: Eminonu ve Kadikoy kiyaslamasi.' },
    { t: 'Vegan bowl haftalik menu: protein kaynagi ve sos cesitliligi.' },
    { t: 'Anadolu mutfagi: tarhana corbasi ve kuru nane ustu.', img: 'tarhana-soup-traditional' },
    { t: 'Lahmacun tas firinda: ince hamur ve kiyma baharat orani.' },
    { t: 'Ev yapimi limonata ve nane: yaz menusune eklendi.', img: 'lemonade-summer-drink' },
    { t: 'Izmir boyoz ve pogaca: kahvalti rituelimiz.' },
    { t: 'Balik ekmek Eminonu: taze levrek ve roka dengesi.' },
    { t: 'Baklava yapimi: ceviz katmani ve serbet sicakligi.', img: 'baklava-pistachio-dessert' },
    { t: 'Kahvalti tabagi: peynir cesitleri ve domates-salatalik.' },
    { t: 'Adana kebap mangal: kuyruk yagi ve lavaş isi.' },
    { t: 'Enginar zeeytinyagli: limon ve dereotu.', img: 'artichoke-olive-oil-food' },
    { t: 'Somon füme salata: avokado ve kapari sos.' },
    { t: 'Ev yapimi ekmek: ekşi maya besleme programi.' },
    { t: 'Kumpir Ortakoy: malzeme secimi ve kalori notu.', img: 'kumpir-street-food' },
    { t: 'Mercimek corbasi: kavrulmus un ve kimyon onemi.' },
    { t: 'Tiramisu: mascarpone sicakligi ve kahve emdirme.' },
    { t: 'Sushi denemesi: pirinc puani ve nori kesimi.', img: 'sushi-japanese-food' },
    { t: 'Manti yogurdu: sarimsak ve nane yagli sos.' },
    { t: 'Firin makarna: bechamel ve kasar ustu kizarma.' },
    { t: 'Soguk ayran ve sicak pide: Ramazan iftar menusu.', img: 'iftar-meal-traditional' },
    { t: 'Dondurma yapimi: vanilya bean ve krema orani.' },
    { t: 'Kis corbasi: brokoli ve cheddar blender.' },
    { t: 'Kahve demleme: V60 pour-over su sicakligi 92C.', img: 'pour-over-coffee' },
  ],
  gaming: [
    { t: 'Baldurs Gate 3 120 saatlik inceleme: hikaye dallanmasi ve companion tasarimi.', img: 'rpg-fantasy-game' },
    { t: 'Indie hafta secimi: Hollow Knight atmosferi ve boss ritmi.', img: 'indie-platform-game' },
    { t: 'Valorant Immortal grind: crosshair ayari ve spray kontrolu.' },
    { t: 'Retro NES koleksiyonu: Zelda ve Metroid orijinal kartuslar.' },
    { t: 'Co-op oyun gecesi: It Takes Two veya Portal 2, Steam daveti acik.', img: 'coop-gaming-couch' },
    { t: 'Elden Ring DLC boss rehberi: faz gecisleri ve build onerisi.' },
    { t: 'Steam yaz indirimleri: wishlist filtreleme taktikleri.', img: 'steam-sale-gaming' },
    { t: 'PlayStation Plus aylik oyunlar: hangileri indirilmeye deger?' },
    { t: 'Minecraft survival sunucusu: redstone otomasyon ve tarim.' },
    { t: 'CS2 smoke atisi: Mirage A site default taktik.', img: 'counter-strike-esports' },
    { t: 'Nintendo Switch OLED ekran kiyaslamasi: handheld mod.' },
    { t: 'Twitch yayin kurulumu: OBS sahneler ve bitrate ayari.', img: 'twitch-stream-setup' },
    { t: 'League of Legends meta notlari: patch sonrasi ADC secimleri.' },
    { t: 'Hades 2 erken erisim: roguelike dongusu ve yetenek agaci.' },
    { t: 'Oyun muzigi Spotify listesi: calisma ve raid icin.', img: 'gaming-music-headset' },
    { t: 'Gamepad dead zone kalibrasyonu: drift sorunu cozumu.' },
    { t: 'Speedrun denemesi: Super Mario 64 16 yildiz rota.' },
    { t: 'VR baslik rahatlik kiyaslamasi: 2 saatlik seans sonrasi.', img: 'vr-headset-gaming' },
    { t: 'Clan turnuvasi: best-of-3 format ve harita veto.' },
    { t: 'Oyun ici ekonomi: trade ve enflasyon analizi (MMO).' },
    { t: 'Mod kurulumu: Nexus Mod Manager adim adim.', img: 'pc-gaming-mod-setup' },
    { t: 'Cocuklar icin ebeveyn kontrolu: sure limiti ve icerik filtresi.' },
    { t: 'Retro Arcade restore: Joystick ve monitor tamiri.' },
    { t: 'Oyun gelistirme: Godot ile 2D platform prototip 1 hafta.', img: 'game-development-godot' },
    { t: 'Arkadaslarla Among Us gecesi: sesli sohbet ve kurallar paketi.' },
  ],
};
